CREATE TABLE ROLES
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT ROLES_pkey PRIMARY KEY (ID)
);

CREATE TABLE USERS
(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    TOKEN VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CONSTRAINT USERS_pkey PRIMARY KEY (ID),
    CONSTRAINT EMAIL_unique UNIQUE (EMAIL),
    CONSTRAINT TOKEN_unique UNIQUE (TOKEN)
);

CREATE TABLE USERS_TO_ROLES
(
    FK_USER_ID BIGINT NOT NULL,
    FK_ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FK_ROLE_TO_USER FOREIGN KEY (FK_ROLE_ID)
        REFERENCES ROLES (ID),
    CONSTRAINT FK_USER_TO_ROLE FOREIGN KEY (FK_USER_ID)
        REFERENCES USERS (ID)
);

CREATE TABLE CATEGORIES
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT CATEGORIES_pkey PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    PRICE DOUBLE,
    DESCRIPTION VARCHAR(255),
    FK_CATEGORIES BIGINT,
    CONSTRAINT PRODUCTS_pkey PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORIES_TO_PRODUCTS FOREIGN KEY (FK_CATEGORIES)
        REFERENCES CATEGORIES (ID)
);

CREATE TABLE CARTS
(
    ID BIGINT NOT NULL,
    AMOUNT BIGINT,
    FK_CUSTOMER_ID BIGINT NOT NULL,
    CONSTRAINT CART_pkey PRIMARY KEY (ID),
    CONSTRAINT FK_USER_TO_CART FOREIGN KEY (FK_CUSTOMER_ID)
        REFERENCES USERS (ID)
);

CREATE TABLE CARTS_DETAILS
(
    FK_CART_ID BIGINT NOT NULL,
    FK_PRODUCT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT FK_CART_TO_PRODUCT FOREIGN KEY (FK_CART_ID)
        REFERENCES CARTS (ID),
    CONSTRAINT FK_PRODUCT_TO_CART FOREIGN KEY (FK_PRODUCT_ID)
        REFERENCES PRODUCTS (ID)
);