INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');

INSERT INTO USERS (EMAIL, PASSWORD, TOKEN, FIRST_NAME, LAST_NAME)
VALUES (
'admin@gmail.com',
'$2a$10$54pc.o9JXMYWRmttEaBUEuion25YpE4KusDsIYERQuW8jGEZZxCK2',
'a4e98b96-813e-446e-a152-f9cc8000a00e',
'BOB',
'MILLER');

INSERT INTO USERS_TO_ROLES (FK_USER_ID, FK_ROLE_ID)
VALUES (2, 1);

INSERT INTO CATEGORIES (NAME, DESCRIPTION)
VALUES ('Mobile', 'Mobile of 2018');

INSERT INTO PRODUCTS (NAME, PRICE, DESCRIPTION, FK_CATEGORIES)
VALUES ('Iphone XS', '1100', 'New Apple mobile', '1');